spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/Exchange}
    username: postgres
    password: AllSafe6
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/realm1xd
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.springframework.security: DEBUG
token:
  converter:
    principal-attribute: preferred_username
    resource-id: backend

